In [1]:
import numpy as np
import random
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
array = np.random.randn(5, 5)
print("2D Array filled with random values : \n", array);

2D Array filled with random values : 
 [[-0.90891227  0.0136969  -0.47091927 -0.26657924  1.09724108]
 [-0.72419828 -0.58874659 -0.57817601  0.18373789  1.03439973]
 [ 2.23991121 -0.72967083 -1.98802227 -1.11589901 -0.28631444]
 [ 0.06120009  0.61262709 -0.11904016  1.7895067   0.1219703 ]
 [-0.01136792 -0.4354301   3.29034601 -0.92013282 -1.1280328 ]]


In [5]:
length = len(array)
r1 = 0
for i in range(length):
    for j in range(5):
         if i==j:
            r1 = r1 + array[i][j]
print(r1) #sum of diagnol
print(abs(r1)) #absolute sum of diagnol

-2.8242072214659015
2.8242072214659015
